/**
 * Q5 — the SHAREABLE session page (`html`, the seventh export format).
 *
 * The other six formats produce markdown you paste somewhere else. This one
 * produces ONE self-contained HTML file you can send to a colleague who wasn't
 * there: inline CSS, zero external requests (the only absolute URL on the page
 * is the footer's repo anchor), works straight off `file://`, respects
 * `prefers-color-scheme`, and prints.
 *
 * Structure (top to bottom):
 *   1. Masthead — project · session · exported-at · deepPairing version.
 *   2. The story — the AGENT-COMPOSED narrative (`narrative`, markdown), or an
 *      honestly-labelled auto-summary when none was supplied.
 *   3. The timeline — replay's chronological event assembly (`buildTimeline`),
 *      with each artifact rendered RICHLY (findings + evidence, decision cards
 *      with every option, spec/plan sections, changeset diffs) and the comment
 *      threads anchored where they happened.
 *   4. Standing stances — rejected approaches with no timestamp to place.
 *   5. Footer — "Generated by deepPairing".
 *
 * HONESTY RULES (the same ones format-markdown carries, restated for a page a
 * stranger reads):
 *   - Rejected / retracted / superseded work is NEVER silently included as if
 *     it shipped, and never silently dropped: its header is struck through and
 *     carries an explicit verdict line ("rejected — <reason>").
 *   - The gate beats render ONLY what the store actually records. Preflight
 *     BLOCKS are not persisted anywhere (the block returns before an artifact
 *     exists, so `preflight-traces.json` — keyed by artifact id — never sees
 *     them; round-12 confirmed the live block is a 12s toast). So the page
 *     renders (a) the STANCES themselves, from session memory, which ARE
 *     timestamped and are what the gate enforces from then on, (b) any
 *     persisted trace, including the `decision: "blocked"` shape should one
 *     ever be recorded, and (c) guardrail hook asks from `hooks-state.json`
 *     when the caller passes them. Nothing is invented.
 *
 * SHARING HYGIENE: absolute paths are relativized against the project root and
 * home-directory prefixes collapse to `~/`; code is INCLUDED by default (the
 * diffs are the point) but `includeCode: false` strips every code body while
 * keeping the file names and shapes.
 */
import type {
  Artifact,
  ChangesetFile,
  Comment,
  CommentTarget,
  DecisionOption,
  Evidence,
} from "@deeppairing/shared";
import {
  coercePlanContent,
  coerceResearchContent,
  coerceReasoningContent,
  coerceDebriefContent,
  coerceExplainerContent,
  coerceSpecContent,
  coerceChangesetContent,
  coerceDecisionContent,
  coerceCodeChangeContent,
} from "@deeppairing/shared";
import { buildTimeline, type TimelineEvent } from "../replay/timeline.js";
import type { DecisionRecord, PlanReviewRecord } from "../store/store-interface.js";

// --- Input shapes -----------------------------------------------------------

/** A rejected approach as session memory records it. Structurally typed so the
 *  renderer stays independent of the store module's exact interface. */
export interface HtmlRejectedApproach {
  description: string;
  reason?: string;
  concept?: string;
  rejectedAt?: string;
  sourceArtifactId?: string;
}

/** A persisted preflight trace (`preflight-traces.json`), loosely typed. */
export interface HtmlPreflightTrace {
  at?: string;
  artifactId?: string;
  toolName?: string;
  decision?: "admitted" | "blocked" | string;
  consideredCount?: number;
  nearMisses?: Array<{ concept?: string; source?: string; coverage?: number }>;
  block?: { source?: string; concept?: string; reason?: string; via?: string };
}

/** One guardrail hook fire as `.deeppairing/hooks-state.json` records it. */
export interface HtmlGuardrailFire {
  at?: string;
  hook?: string;
  reason?: string;
}

export interface HtmlSessionState {
  sessionId: string;
  artifacts: Artifact[];
  comments: Comment[];
  decisions: Array<{
    decisionId: string;
    artifactId: string;
    context: string;
    title?: string;
    options: DecisionOption[];
    response?: { optionId: string; reasoning?: string };
    createdAt: string;
    resolvedAt?: string;
  }>;
  planReviews: Array<{
    artifactId: string;
    verdict?: string;
    feedback?: string;
    createdAt?: string;
    resolvedAt?: string;
  }>;
  /** Attached by the caller — `getFullState()` already carries it. */
  sessionMemory?: { rejectedApproaches?: HtmlRejectedApproach[]; approvedPatterns?: string[] };
  /** Attached by the caller (per-artifact `getPreflightTrace` gather). */
  preflightTraces?: HtmlPreflightTrace[];
  /** Attached by the caller (project-scoped `hooks-state.json` fire log). */
  guardrailFires?: HtmlGuardrailFire[];
}

export interface HtmlExportOptions {
  /** The agent-composed story, markdown. Rendered at the top of the page. */
  narrative?: string;
  /** Optional hint about who this was written for ("the backend team"). */
  audience?: string;
  /** INCLUDE code bodies (diffs, snippets, before/after). Default true. */
  includeCode?: boolean;
  /** Human-facing project name for the masthead. */
  projectName?: string;
  /** Absolute project root — used ONLY to relativize absolute file paths. */
  projectRoot?: string;
  /** deepPairing version stamp for the masthead + footer. */
  version?: string;
  /** ISO export timestamp. Injectable so tests are deterministic. */
  generatedAt?: string;
}

// --- Size sanity ------------------------------------------------------------
//
// A big session must still be ONE reasonable file. Every cap truncates
// HONESTLY (an explicit "… truncated" line naming how much was dropped) and
// long diffs collapse behind <details> rather than being cut.

const MAX_SNIPPET_LINES = 40;
const MAX_CODE_LINES = 120;
const MAX_DIFF_LINES_PER_FILE = 400;
const DIFF_COLLAPSE_THRESHOLD = 24;
const REPO_URL = "https://github.com/mitchjablonski/deepPairing";

// --- Marks ------------------------------------------------------------------
//
// INLINE SVG, not emoji. The page is sent to strangers on unknown machines and
// prints; a headless/Linux reader without an emoji font renders ⛔/🛡 as tofu
// boxes (the same defect round 12 found in the hero toast). These inherit
// currentColor and cost nothing.

const BLOCK_MARK =
  '<span class="gate-mark"><svg viewBox="0 0 16 16" width="15" height="15" fill="none" ' +
  'stroke="currentColor" stroke-width="1.7" aria-hidden="true"><circle cx="8" cy="8" r="6.2"/>' +
  '<path d="M4.2 8h7.6"/></svg></span>';

const SHIELD_MARK =
  '<span class="gate-mark"><svg viewBox="0 0 16 16" width="15" height="15" fill="none" ' +
  'stroke="currentColor" stroke-width="1.7" stroke-linejoin="round" aria-hidden="true">' +
  '<path d="M8 1.8 13 3.6v4.2c0 3-2.1 5.3-5 6.4-2.9-1.1-5-3.4-5-6.4V3.6z"/></svg></span>';

// --- Primitives -------------------------------------------------------------

function esc(value: unknown): string {
  const s = value == null ? "" : String(value);
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/** Home-directory + project-root stripping so a shared page never carries the
 *  exporter's username or machine layout. Repo-relative paths pass through. */
export function sanitizePath(raw: unknown, projectRoot?: string): string {
  let p = typeof raw === "string" ? raw.trim() : "";
  if (!p) return "";
  const normalized = p.replace(/\\/g, "/");
  if (projectRoot) {
    const root = projectRoot.replace(/\\/g, "/").replace(/\/+$/, "");
    if (root && normalized.startsWith(root + "/")) return normalized.slice(root.length + 1);
    if (root && normalized === root) return ".";
  }
  p = normalized;
  // /home/<user>/…, /Users/<user>/…, C:/Users/<user>/… → ~/…
  p = p.replace(/^(?:[A-Za-z]:)?\/(?:home|Users)\/[^/]+\//, "~/");
  return p;
}

function fmtTimestamp(iso?: string): string {
  if (!iso) return "";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return String(iso);
  return d.toISOString().replace("T", " ").slice(0, 16) + " UTC";
}

function fmtDay(iso?: string): string {
  if (!iso) return "";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return String(iso);
  return d.toISOString().slice(0, 10);
}

function plural(n: number, one: string, many = one + "s"): string {
  return `${n} ${n === 1 ? one : many}`;
}

// --- The tiny markdown renderer ---------------------------------------------
//
// Deliberately small and dependency-free (the page must build with zero new
// deps and stay self-contained). Covers what an agent-composed narrative
// actually uses: headings, paragraphs, bold/italic/inline-code, fenced code,
// bullet + numbered lists, blockquotes, links, and rules. Everything is
// ESCAPED first, so unmatched syntax degrades to literal text — never markup.

const SAFE_URL = /^(?:https?:\/\/|mailto:|#|\/|\.{1,2}\/)/i;

function renderInline(text: string): string {
  // Escape first — every transform below operates on already-safe text.
  let out = esc(text);
  // Protect code spans from the emphasis passes.
  const codeSpans: string[] = [];
  out = out.replace(/`([^`]+)`/g, (_m, code: string) => {
    codeSpans.push(`<code>${code}</code>`);
    return `\u0000CODE${codeSpans.length - 1}\u0000`;
  });
  out = out.replace(/\[([^\]]+)\]\(([^)\s]+)\)/g, (_m, label: string, url: string) => {
    const raw = url.replace(/&amp;/g, "&");
    if (!SAFE_URL.test(raw)) return label;
    return `<a href="${esc(raw)}" rel="noopener noreferrer">${label}</a>`;
  });
  out = out.replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
  out = out.replace(/(^|[^*\w])\*([^*\n]+)\*(?!\*)/g, "$1<em>$2</em>");
  out = out.replace(/(^|[^_\w])_([^_\n]+)_(?![\w_])/g, "$1<em>$2</em>");
  out = out.replace(/\u0000CODE(\d+)\u0000/g, (_m, i: string) => codeSpans[Number(i)] ?? "");
  return out;
}

/**
 * Render a markdown subset to HTML. `baseHeading` is the level a top-level `#`
 * maps to (the narrative sits under an <h2>, so its own headings start at h3
 * and the document outline stays sane).
 */
export function renderMarkdown(md: string, baseHeading = 3): string {
  const lines = String(md ?? "").replace(/\r\n?/g, "\n").split("\n");
  // noUncheckedIndexedAccess is on repo-wide: read every line through `at`.
  const at = (k: number): string => lines[k] ?? "";
  const out: string[] = [];
  let i = 0;

  const flushList = (tag: "ul" | "ol", items: string[]) => {
    out.push(`<${tag}>`);
    for (const item of items) out.push(`<li>${renderInline(item)}</li>`);
    out.push(`</${tag}>`);
  };

  while (i < lines.length) {
    const line = at(i);

    if (/^\s*$/.test(line)) { i++; continue; }

    // Fenced code
    const fence = line.match(/^\s*```(\w+)?\s*$/);
    if (fence) {
      const body: string[] = [];
      i++;
      while (i < lines.length && !/^\s*```\s*$/.test(at(i))) { body.push(at(i)); i++; }
      i++; // closing fence
      out.push(codeBlock(body.join("\n"), { language: fence[1], maxLines: MAX_CODE_LINES }));
      continue;
    }

    // Horizontal rule
    if (/^\s*(?:-{3,}|\*{3,}|_{3,})\s*$/.test(line)) { out.push("<hr />"); i++; continue; }

    // Heading
    const h = line.match(/^\s*(#{1,6})\s+(.*)$/);
    if (h) {
      const level = Math.min(6, baseHeading + (h[1] ?? "#").length - 1);
      out.push(`<h${level}>${renderInline((h[2] ?? "").trim())}</h${level}>`);
      i++;
      continue;
    }

    // Blockquote
    if (/^\s*>\s?/.test(line)) {
      const body: string[] = [];
      while (i < lines.length && /^\s*>\s?/.test(at(i))) {
        body.push(at(i).replace(/^\s*>\s?/, ""));
        i++;
      }
      out.push(`<blockquote>${renderMarkdown(body.join("\n"), baseHeading)}</blockquote>`);
      continue;
    }

    // Unordered list
    if (/^\s*[-*+]\s+/.test(line)) {
      const items: string[] = [];
      while (i < lines.length && /^\s*[-*+]\s+/.test(at(i))) {
        items.push(at(i).replace(/^\s*[-*+]\s+/, ""));
        i++;
      }
      flushList("ul", items);
      continue;
    }

    // Ordered list
    if (/^\s*\d+[.)]\s+/.test(line)) {
      const items: string[] = [];
      while (i < lines.length && /^\s*\d+[.)]\s+/.test(at(i))) {
        items.push(at(i).replace(/^\s*\d+[.)]\s+/, ""));
        i++;
      }
      flushList("ol", items);
      continue;
    }

    // Paragraph
    const para: string[] = [];
    while (
      i < lines.length &&
      !/^\s*$/.test(at(i)) &&
      !/^\s*```/.test(at(i)) &&
      !/^\s*#{1,6}\s+/.test(at(i)) &&
      !/^\s*>/.test(at(i)) &&
      !/^\s*[-*+]\s+/.test(at(i)) &&
      !/^\s*\d+[.)]\s+/.test(at(i))
    ) {
      para.push(at(i));
      i++;
    }
    out.push(`<p>${renderInline(para.join("\n"))}</p>`);
  }

  return out.join("\n");
}

// --- Code rendering ---------------------------------------------------------

interface CodeBlockOptions {
  language?: string;
  maxLines?: number;
  /** false → the body is replaced by an honest "code omitted" note. */
  includeCode?: boolean;
  label?: string;
}

/** A legible, syntax-highlight-free pre/mono block with an honest truncation
 *  marker. `includeCode: false` keeps the shape, drops the body. */
function codeBlock(text: string, opts: CodeBlockOptions = {}): string {
  const { language, maxLines = MAX_CODE_LINES, includeCode = true, label } = opts;
  const head = label ? `<p class="code-label">${esc(label)}</p>` : "";
  if (includeCode === false) {
    const lineCount = String(text ?? "").split("\n").length;
    return `${head}<p class="redacted">Code omitted from this export (${plural(lineCount, "line")}).</p>`;
  }
  const all = String(text ?? "").replace(/\r\n?/g, "\n").split("\n");
  const shown = all.slice(0, maxLines);
  const omitted = all.length - shown.length;
  const body = esc(shown.join("\n"));
  const trunc = omitted > 0
    ? `\n<span class="truncated">… truncated — ${plural(omitted, "more line")} not shown</span>`
    : "";
  const langAttr = language ? ` data-language="${esc(language)}"` : "";
  return `${head}<pre class="code"${langAttr}><code>${body}${trunc}</code></pre>`;
}

/** Per-file unified diff. Long diffs collapse behind <details> rather than
 *  being cut, so the page stays skimmable without losing the record. */
function diffBlock(file: ChangesetFile, includeCode: boolean, projectRoot?: string): string {
  const path = sanitizePath(file.path, projectRoot);
  const changeType = esc(file.changeType ?? "modified");
  const hunks = Array.isArray(file.hunks) ? file.hunks : [];
  const stats = file.stats;
  const derived = hunks.reduce(
    (acc, h) => {
      for (const l of h?.lines ?? []) {
        if (l?.kind === "add") acc.additions++;
        else if (l?.kind === "del") acc.deletions++;
      }
      return acc;
    },
    { additions: 0, deletions: 0 },
  );
  const additions = stats?.additions ?? derived.additions;
  const deletions = stats?.deletions ?? derived.deletions;
  const statLine =
    `<span class="diffstat"><span class="add">+${additions}</span> <span class="del">−${deletions}</span></span>`;

  const header =
    `<div class="file-head"><code class="path">${esc(path)}</code>` +
    `<span class="chip chip--${changeType}">${changeType}</span>${statLine}</div>`;

  if (!includeCode) {
    return `<div class="file">${header}<p class="redacted">Diff omitted from this export.</p></div>`;
  }

  const rows: string[] = [];
  let emitted = 0;
  let dropped = 0;
  for (const hunk of hunks) {
    if (hunk?.header) {
      rows.push(`<div class="dl dl--hunk">${esc(hunk.header)}</div>`);
    }
    for (const line of hunk?.lines ?? []) {
      if (emitted >= MAX_DIFF_LINES_PER_FILE) { dropped++; continue; }
      const kind = line?.kind === "add" ? "add" : line?.kind === "del" ? "del" : "ctx";
      const sign = kind === "add" ? "+" : kind === "del" ? "-" : " ";
      const num = kind === "del" ? line?.oldLine : line?.newLine;
      rows.push(
        `<div class="dl dl--${kind}"><span class="ln">${num == null ? "" : esc(num)}</span>` +
        `<span class="sign">${sign}</span><span class="src">${esc(line?.content ?? "")}</span></div>`,
      );
      emitted++;
    }
  }
  if (dropped > 0) {
    rows.push(`<div class="dl dl--trunc">… truncated — ${plural(dropped, "more diff line")} not shown</div>`);
  }

  const diff = `<div class="diff">${rows.join("")}</div>`;
  const body = emitted > DIFF_COLLAPSE_THRESHOLD
    ? `<details><summary>Show the diff (${plural(emitted, "line")})</summary>${diff}</details>`
    : diff;
  return `<div class="file">${header}${body}</div>`;
}

// --- Evidence ---------------------------------------------------------------

function evidenceBlock(evidence: unknown, includeCode: boolean, projectRoot?: string): string {
  if (!Array.isArray(evidence)) {
    if (typeof evidence === "string" && evidence.trim()) {
      return `<p class="evidence-note">${renderInline(evidence)}</p>`;
    }
    return "";
  }
  const parts: string[] = [];
  for (const ev of evidence) {
    if (typeof ev === "string") {
      if (ev.trim()) parts.push(`<p class="evidence-note">${renderInline(ev)}</p>`);
      continue;
    }
    if (!ev || typeof ev !== "object") continue;
    const e = ev as Evidence;
    const path = sanitizePath(e.filePath, projectRoot);
    const range = e.lineStart != null
      ? `:${e.lineStart}${e.lineEnd != null && e.lineEnd !== e.lineStart ? `-${e.lineEnd}` : ""}`
      : "";
    const anchor = path ? `<p class="anchor"><code>${esc(path + range)}</code></p>` : "";
    const snippet = e.snippet
      ? codeBlock(e.snippet, { language: e.language, maxLines: MAX_SNIPPET_LINES, includeCode })
      : "";
    const explanation = e.explanation ? `<p class="evidence-note">${renderInline(e.explanation)}</p>` : "";
    parts.push(`<div class="evidence">${anchor}${snippet}${explanation}</div>`);
  }
  return parts.join("");
}

// --- Comments ---------------------------------------------------------------

/** Human-readable "where this comment landed", from the comment target. */
function anchorLabel(c: Comment, projectRoot?: string): string {
  const t = (c.target ?? {}) as CommentTarget;
  const bits: string[] = [];
  if (t.filePath) {
    const line = t.lineStart ?? t.lineNumber;
    bits.push(`${sanitizePath(t.filePath, projectRoot)}${line != null ? `:${line}` : ""}${t.side === "old" ? " (removed line)" : ""}`);
  } else if (t.lineStart != null || t.lineNumber != null) {
    bits.push(`line ${t.lineStart ?? t.lineNumber}`);
  }
  if (t.findingIndex != null) bits.push(`finding #${t.findingIndex + 1}`);
  if (t.evidenceIndex != null) bits.push(`evidence #${t.evidenceIndex + 1}`);
  if (t.stepIndex != null) bits.push(`step ${t.stepIndex + 1}`);
  if (t.requirementId) bits.push(`requirement ${t.requirementId}`);
  if (t.optionId) bits.push(`option ${t.optionId}`);
  if (t.questionIndex != null) bits.push(`open question #${t.questionIndex + 1}`);
  if (t.sectionId) bits.push(`section ${t.sectionId}`);
  if (t.visualId) bits.push(t.region ? "a region of the diagram" : "the diagram");
  if (Array.isArray(t.anchors) && t.anchors.length > 1) bits.push(`${t.anchors.length} linked locations`);
  return bits.join(" · ");
}

function commentHtml(c: Comment, includeCode: boolean, projectRoot?: string): string {
  const who = c.author === "agent" ? "The agent" : "The human";
  const intent = c.intent;
  const intentChip = intent && intent !== "comment"
    ? `<span class="chip chip--${esc(intent)}">${esc(intent)}</span>`
    : "";
  const anchor = anchorLabel(c, projectRoot);
  const anchorHtml = anchor ? `<span class="thread-anchor">on ${esc(anchor)}</span>` : "";
  const sug = c.suggestion;
  let sugHtml = "";
  if (sug) {
    const state = sug.state ? `<span class="chip chip--${esc(sug.state)}">suggestion ${esc(sug.state)}</span>` : "";
    const replacement = sug.replacementText
      ? codeBlock(sug.replacementText, { includeCode, maxLines: MAX_SNIPPET_LINES, label: "Suggested instead" })
      : "";
    const counter = sug.counter?.replacementText
      ? codeBlock(sug.counter.replacementText, { includeCode, maxLines: MAX_SNIPPET_LINES, label: "The agent's counter" })
      : "";
    const counterReason = sug.counter?.reason ? `<p>${renderInline(sug.counter.reason)}</p>` : "";
    sugHtml = `<div class="suggestion">${state}${replacement}${counter}${counterReason}</div>`;
  }
  return (
    `<li class="thread-item thread-item--${c.author === "agent" ? "agent" : "human"}">` +
    `<div class="thread-meta"><span class="who">${esc(who)}</span>${intentChip}${anchorHtml}` +
    `<time>${esc(fmtTimestamp(c.createdAt))}</time></div>` +
    `<div class="thread-body">${renderMarkdown(c.content ?? "", 5)}</div>${sugHtml}</li>`
  );
}

function threadHtml(comments: Comment[], includeCode: boolean, projectRoot?: string, heading = "Discussion"): string {
  if (comments.length === 0) return "";
  const items = comments
    .slice()
    .sort((a, b) => String(a.createdAt).localeCompare(String(b.createdAt)))
    .map((c) => commentHtml(c, includeCode, projectRoot))
    .join("");
  return `<div class="thread"><h4 class="thread-head">${esc(heading)} (${comments.length})</h4><ul class="thread-list">${items}</ul></div>`;
}

// --- Artifact bodies --------------------------------------------------------

interface RenderCtx {
  state: HtmlSessionState;
  includeCode: boolean;
  projectRoot?: string;
  /** artifactId → comments, minus any already rendered under a diff file. */
  commentsByArtifact: Map<string, Comment[]>;
}

function researchBody(a: Artifact, ctx: RenderCtx): string {
  const content = coerceResearchContent(a.content);
  const parts: string[] = [];
  if (content.summary) parts.push(renderMarkdown(content.summary, 4));
  for (const f of content.findings ?? []) {
    // significance (note-worthiness) and severity (risk) are DIFFERENT axes
    // that often carry the same word — name each so two "HIGH" chips beside
    // each other don't read as a duplicate.
    const sig = f.significance ? `<span class="chip chip--sig-${esc(f.significance)}">${esc(f.significance)} significance</span>` : "";
    const sev = f.severity ? `<span class="chip chip--sev-${esc(f.severity)}">${esc(f.severity)} severity</span>` : "";
    const cat = f.category ? `<span class="chip">${esc(f.category)}</span>` : "";
    parts.push(
      `<div class="finding"><h4>${esc(f.title ?? f.category ?? "Finding")}</h4>` +
      `<div class="chips">${sig}${sev}${cat}</div>` +
      renderMarkdown(f.detail ?? "", 5) +
      evidenceBlock(f.evidence, ctx.includeCode, ctx.projectRoot) +
      (f.impact ? `<p class="kv"><span class="k">Impact</span> ${renderInline(f.impact)}</p>` : "") +
      (f.recommendation ? `<p class="kv"><span class="k">Recommendation</span> ${renderInline(f.recommendation)}</p>` : "") +
      `</div>`,
    );
  }
  for (const q of content.openQuestions ?? []) {
    parts.push(`<p class="open-question">Open question: ${renderInline(q)}</p>`);
  }
  return parts.join("");
}

function specBody(a: Artifact, _ctx: RenderCtx): string {
  const content = coerceSpecContent(a.content);
  const parts: string[] = [];
  if (content.objective) parts.push(`<p class="kv"><span class="k">Objective</span> ${renderInline(content.objective)}</p>`);
  if (content.context) parts.push(renderMarkdown(content.context, 4));
  if (content.requirements?.length) {
    parts.push(`<h4>Requirements</h4><ul class="req-list">`);
    for (const r of content.requirements) {
      const pri = r.priority ? `<span class="chip">${esc(r.priority)}</span>` : "";
      const why = r.rationale ? `<p class="why">Why: ${renderInline(r.rationale)}</p>` : "";
      const ac = (r.acceptanceCriteria ?? []).map((c) => `<li>${renderInline(c)}</li>`).join("");
      parts.push(
        `<li><div class="req-head"><code>${esc(r.id)}</code>${pri}</div>` +
        `<p>${renderInline(r.statement)}</p>${why}` +
        (ac ? `<ul class="criteria">${ac}</ul>` : "") + `</li>`,
      );
    }
    parts.push(`</ul>`);
  }
  if (content.design) parts.push(`<h4>Design</h4>${renderMarkdown(content.design, 5)}`);
  if (content.tasks?.length) {
    parts.push(`<h4>Tasks</h4><ul>${content.tasks.map((t) => `<li>${renderInline(t.description)}</li>`).join("")}</ul>`);
  }
  for (const q of content.openQuestions ?? []) {
    parts.push(`<p class="open-question">Open question: ${renderInline(q)}</p>`);
  }
  return parts.join("");
}

function planBody(a: Artifact, ctx: RenderCtx): string {
  const content = coercePlanContent(a.content);
  const parts: string[] = [];
  if (content.estimatedChanges != null && content.estimatedChanges !== "") {
    parts.push(`<p class="kv"><span class="k">Estimated size</span> ${esc(content.estimatedChanges)}</p>`);
  }
  parts.push(`<ol class="steps">`);
  for (const step of content.steps ?? []) {
    const files = Array.isArray(step.files)
      ? step.files
          .map((f) => sanitizePath(typeof f === "string" ? f : f.filePath, ctx.projectRoot))
          .filter(Boolean)
      : [];
    const fileHtml = files.length
      ? `<p class="files">${files.map((f) => `<code>${esc(f)}</code>`).join(" ")}</p>`
      : "";
    const status = step.status ? `<span class="chip chip--${esc(step.status)}">${esc(step.status)}</span>` : "";
    const preview = step.preview
      ? codeBlock(step.preview.after ?? "", {
          includeCode: ctx.includeCode,
          maxLines: MAX_SNIPPET_LINES,
          label: `After — ${sanitizePath(step.preview.filePath, ctx.projectRoot)}`,
        })
      : "";
    parts.push(
      `<li><div class="step-head">${renderInline(step.description)}${status}</div>` +
      (step.reasoning ? `<p class="why">Why: ${renderInline(step.reasoning)}</p>` : "") +
      fileHtml + preview + `</li>`,
    );
  }
  parts.push(`</ol>`);
  return parts.join("");
}

function decisionBody(a: Artifact, ctx: RenderCtx): string {
  const content = coerceDecisionContent(a.content);
  const record = ctx.state.decisions.find(
    (d) => d.decisionId === content.decisionId || d.artifactId === a.id,
  );
  const chosenId = record?.response?.optionId;
  const parts: string[] = [];
  if (content.context) parts.push(renderMarkdown(content.context, 4));
  parts.push(`<div class="options">`);
  for (const o of content.options ?? []) {
    const chosen = chosenId != null && o.id === chosenId;
    const badge = chosen
      ? `<span class="chip chip--chosen">chosen</span>`
      : chosenId != null
        ? `<span class="chip chip--notchosen">not taken</span>`
        : "";
    const rec = o.recommendation ? `<span class="chip">agent's pick</span>` : "";
    const pros = (o.pros ?? []).map((p) => `<li>${renderInline(p)}</li>`).join("");
    const cons = (o.cons ?? []).map((p) => `<li>${renderInline(p)}</li>`).join("");
    const concept = o.concept?.name
      ? `<p class="concept">Pattern: <strong>${esc(o.concept.name)}</strong>` +
        (o.concept.oneLineExplanation ? ` — ${renderInline(o.concept.oneLineExplanation)}` : "") +
        `</p>`
      : "";
    parts.push(
      `<div class="option${chosen ? " option--chosen" : ""}">` +
      `<div class="option-head"><h4>${esc(o.title ?? o.id)}</h4>${badge}${rec}</div>` +
      `<div class="chips"><span class="chip">effort: ${esc(o.effort ?? "?")}</span><span class="chip">risk: ${esc(o.risk ?? "?")}</span></div>` +
      (o.description ? `<p>${renderInline(o.description)}</p>` : "") + concept +
      (pros ? `<p class="k">Pros</p><ul class="pros">${pros}</ul>` : "") +
      (cons ? `<p class="k">Cons</p><ul class="cons">${cons}</ul>` : "") +
      `</div>`,
    );
  }
  parts.push(`</div>`);
  if (record?.response) {
    const chosenOption = (content.options ?? []).find((o) => o.id === chosenId);
    parts.push(
      `<div class="verdict verdict--chosen"><strong>The human chose:</strong> ${esc(chosenOption?.title ?? chosenId ?? "")}` +
      (record.response.reasoning ? ` — “${renderInline(record.response.reasoning)}”` : "") +
      `</div>`,
    );
  } else {
    parts.push(`<p class="pending">No answer recorded for this fork.</p>`);
  }
  return parts.join("");
}

function codeChangeBody(a: Artifact, ctx: RenderCtx): string {
  const content = coerceCodeChangeContent(a.content);
  const path = sanitizePath(content.filePath, ctx.projectRoot);
  const parts: string[] = [
    `<div class="file-head"><code class="path">${esc(path)}</code>` +
    `<span class="chip chip--${esc(content.changeType)}">${esc(content.changeType)}</span></div>`,
  ];
  if (content.reasoning) parts.push(`<p class="why">Why: ${renderInline(content.reasoning)}</p>`);
  if (content.concept?.name) {
    parts.push(
      `<p class="concept">Pattern: <strong>${esc(content.concept.name)}</strong>` +
      (content.concept.oneLineExplanation ? ` — ${renderInline(content.concept.oneLineExplanation)}` : "") +
      `</p>`,
    );
  }
  const after = codeBlock(content.after ?? "", {
    includeCode: ctx.includeCode,
    maxLines: MAX_CODE_LINES,
    label: content.changeType === "delete" ? "Removed" : "After",
  });
  const beforeBody = content.before
    ? codeBlock(content.before, { includeCode: ctx.includeCode, maxLines: MAX_CODE_LINES, label: "Before" })
    : "";
  const beforeLines = String(content.before ?? "").split("\n").length;
  parts.push(
    beforeBody
      ? beforeLines > DIFF_COLLAPSE_THRESHOLD
        ? `<details><summary>Show the previous version (${plural(beforeLines, "line")})</summary>${beforeBody}</details>`
        : beforeBody
      : "",
  );
  parts.push(after);
  return parts.join("");
}

function changesetBody(a: Artifact, ctx: RenderCtx, ownComments: Comment[]): string {
  const content = coerceChangesetContent(a.content);
  const parts: string[] = [];
  if (content.summary) parts.push(renderMarkdown(content.summary, 4));
  if (content.risks?.length) {
    parts.push(`<div class="chips">${content.risks.map((r) => `<span class="chip chip--risk">${esc(r)}</span>`).join("")}</div>`);
  }
  for (const file of content.files ?? []) {
    const disposition = content.reviewState?.[file.path];
    const reason = content.reviewReasons?.[file.path];
    const dispHtml = disposition
      ? `<p class="disposition">Reviewed as <strong>${esc(disposition)}</strong>${reason ? ` — ${renderInline(reason)}` : ""}</p>`
      : "";
    // Comments anchored to THIS file render right under its diff — where they
    // happened — and are removed from the artifact's Discussion block.
    const fileComments = ownComments.filter((c) => c.target?.filePath === file.path);
    for (const c of fileComments) {
      const idx = ownComments.indexOf(c);
      if (idx >= 0) ownComments.splice(idx, 1);
    }
    parts.push(
      `<div class="file-wrap">${diffBlock(file, ctx.includeCode, ctx.projectRoot)}${dispHtml}` +
      threadHtml(fileComments, ctx.includeCode, ctx.projectRoot, "On this file") + `</div>`,
    );
  }
  return parts.join("");
}

function debriefBody(a: Artifact, ctx: RenderCtx): string {
  const content = coerceDebriefContent(a.content);
  const parts: string[] = [];
  if (content.summary) parts.push(renderMarkdown(content.summary, 4));
  for (const s of content.sections ?? []) {
    parts.push(
      `<div class="walk-section"><h4>${esc(s.title)}</h4>` +
      (s.body ? renderMarkdown(s.body, 5) : "") +
      (s.concepts ?? [])
        .map((c) => `<p class="concept">Pattern: <strong>${esc(c.name)}</strong>${c.oneLineExplanation ? ` — ${renderInline(c.oneLineExplanation)}` : ""}</p>`)
        .join("") +
      evidenceBlock(s.evidence, ctx.includeCode, ctx.projectRoot) + `</div>`,
    );
  }
  if (content.decisionsMade?.length) {
    parts.push(
      `<h4>Calls the agent made on its own</h4><ul>` +
      content.decisionsMade
        .map((d) => `<li><strong>${esc(d.what)}</strong> — ${renderInline(d.why)}${d.alternative ? ` <em>(considered: ${esc(d.alternative)})</em>` : ""}</li>`)
        .join("") + `</ul>`,
    );
  }
  if (content.needsYourEyes?.length) {
    parts.push(
      `<div class="needs-eyes"><h4>Needs a human's eyes</h4><ul>` +
      content.needsYourEyes.map((n) => `<li><strong>${esc(n.what)}</strong> — ${renderInline(n.why)}</li>`).join("") +
      `</ul></div>`,
    );
  }
  if (content.deferred?.length) {
    parts.push(
      `<h4>Deferred</h4><ul>` +
      content.deferred.map((d) => `<li><strong>${esc(d.what)}</strong> — ${renderInline(d.why)}</li>`).join("") + `</ul>`,
    );
  }
  if (content.openQuestions?.length) {
    parts.push(`<h4>Open questions</h4><ul>${content.openQuestions.map((q: string) => `<li>${renderInline(q)}</li>`).join("")}</ul>`);
  }
  return parts.join("");
}

function explainerBody(a: Artifact, ctx: RenderCtx): string {
  const content = coerceExplainerContent(a.content);
  const parts: string[] = [];
  if (content.overview) parts.push(renderMarkdown(content.overview, 4));
  (content.sections ?? []).forEach((s, i) => {
    parts.push(
      `<div class="walk-section"><h4>${i + 1}. ${esc(s.heading ?? "")}</h4>` +
      (s.body ? renderMarkdown(s.body, 5) : "") +
      evidenceBlock(s.evidence, ctx.includeCode, ctx.projectRoot) + `</div>`,
    );
  });
  return parts.join("");
}

function reasoningBody(a: Artifact): string {
  const content = coerceReasoningContent(a.content);
  const concept = content.concept?.name
    ? `<p class="concept">Pattern: <strong>${esc(content.concept.name)}</strong>${content.concept.oneLineExplanation ? ` — ${renderInline(content.concept.oneLineExplanation)}` : ""}</p>`
    : "";
  return (
    (content.action ? `<p class="kv"><span class="k">Action</span> ${renderInline(content.action)}</p>` : "") +
    (content.reasoning ? renderMarkdown(content.reasoning, 5) : "") +
    (content.confidence ? `<p class="kv"><span class="k">Confidence</span> ${esc(content.confidence)}</p>` : "") +
    concept
  );
}

function artifactBody(a: Artifact, ctx: RenderCtx, ownComments: Comment[]): string {
  switch (a.type) {
    case "research": return researchBody(a, ctx);
    case "spec": return specBody(a, ctx);
    case "plan": return planBody(a, ctx);
    case "decision": return decisionBody(a, ctx);
    case "code_change": return codeChangeBody(a, ctx);
    case "changeset": return changesetBody(a, ctx, ownComments);
    case "debrief": return debriefBody(a, ctx);
    case "explainer": return explainerBody(a, ctx);
    case "reasoning": return reasoningBody(a);
    default:
      return `<p class="pending">(${esc(a.type)} — no renderer; nothing invented.)</p>`;
  }
}

// --- Honesty markers --------------------------------------------------------

const NOT_SHIPPED = new Set(["rejected", "retracted", "superseded", "obsolete"]);

/** The verdict line for work that did NOT ship — struck header + why, joined to
 *  the recorded rejection reason when session memory carries one. */
function verdictLine(a: Artifact, state: HtmlSessionState): string {
  if (!NOT_SHIPPED.has(a.status)) return "";
  const stances = state.sessionMemory?.rejectedApproaches ?? [];
  const match = stances.find(
    (r) => r.sourceArtifactId === a.id || (r.description && r.description === a.title),
  );
  const reason = match?.reason ? ` — “${esc(match.reason)}”` : "";
  switch (a.status) {
    case "rejected":
      return `<p class="verdict verdict--rejected">rejected: the human declined this${reason}. It is here for the record, not as part of what shipped.</p>`;
    case "retracted":
      return `<p class="verdict verdict--rejected">retracted: the agent withdrew this${reason}.</p>`;
    case "superseded":
      return `<p class="verdict verdict--superseded">superseded: a later version replaced this one.</p>`;
    default:
      return `<p class="verdict verdict--superseded">obsolete: the discussion overtook this.</p>`;
  }
}

// --- Beats ------------------------------------------------------------------

interface Beat {
  at: string;
  /** Insertion order — stable tiebreak for identical timestamps. */
  seq: number;
  html: string;
}

function beat(at: string, seq: number, html: string): Beat {
  return { at: at ?? "", seq, html };
}

function artifactBeat(a: Artifact, ctx: RenderCtx, seq: number): Beat {
  const own = (ctx.commentsByArtifact.get(a.id) ?? []).slice();
  const notShipped = NOT_SHIPPED.has(a.status);
  const title = esc(a.title || a.type);
  const heading = notShipped ? `<s>${title}</s>` : title;
  const version = a.version > 1 ? `<span class="chip">v${a.version}</span>` : "";
  // changesetBody consumes the per-file comments out of `own`, so render the
  // body BEFORE the leftover Discussion block.
  const body = artifactBody(a, ctx, own);
  return beat(
    a.createdAt,
    seq,
    `<li class="beat beat--artifact${notShipped ? " beat--not-shipped" : ""}" id="artifact-${esc(a.id)}">` +
    `<div class="beat-head"><time>${esc(fmtTimestamp(a.createdAt))}</time>` +
    `<span class="chip chip--type">${esc(a.type)}</span>${version}</div>` +
    `<h3>${heading}</h3>${verdictLine(a, ctx.state)}` +
    `<div class="beat-body">${body}</div>` +
    threadHtml(own, ctx.includeCode, ctx.projectRoot) +
    `</li>`,
  );
}

function statusBeat(event: TimelineEvent, seq: number): Beat {
  const status = String((event.payload ?? {}).status ?? "");
  const cls = status === "approved" ? "ok" : status === "rejected" ? "bad" : "neutral";
  return beat(
    event.at,
    seq,
    `<li class="beat beat--status beat--${cls}"><time>${esc(fmtTimestamp(event.at))}</time>` +
    `<span class="beat-line">${esc(event.label)}</span></li>`,
  );
}

function decisionBeat(event: TimelineEvent, seq: number): Beat {
  const p = event.payload ?? {};
  const rejectedTitles = Array.isArray(p.rejectedTitles) ? (p.rejectedTitles as unknown[]) : [];
  const rejected = rejectedTitles.length
    ? `<p class="not-taken">Not taken: ${rejectedTitles.map((t) => esc(t)).join(", ")}</p>`
    : "";
  return beat(
    event.at,
    seq,
    `<li class="beat beat--decided"><time>${esc(fmtTimestamp(event.at))}</time>` +
    `<h3>Decided: ${esc(p.chosenTitle ?? p.chosenOptionId ?? "")}</h3>` +
    (p.reasoning ? `<blockquote class="human-reason">${renderInline(String(p.reasoning))}</blockquote>` : "") +
    rejected + `</li>`,
  );
}

function planReviewBeat(event: TimelineEvent, seq: number): Beat {
  const p = event.payload ?? {};
  return beat(
    event.at,
    seq,
    `<li class="beat beat--review"><time>${esc(fmtTimestamp(event.at))}</time>` +
    `<span class="beat-line">Plan review: <strong>${esc(p.verdict ?? "")}</strong></span>` +
    (p.feedback ? `<blockquote class="human-reason">${renderInline(String(p.feedback))}</blockquote>` : "") + `</li>`,
  );
}

function looseCommentBeat(c: Comment, ctx: RenderCtx, seq: number): Beat {
  return beat(
    c.createdAt,
    seq,
    `<li class="beat beat--comment"><time>${esc(fmtTimestamp(c.createdAt))}</time>` +
    `<ul class="thread-list">${commentHtml(c, ctx.includeCode, ctx.projectRoot)}</ul></li>`,
  );
}

/**
 * A stance the human recorded — the gate moment made shareable. This is what
 * the preflight gate enforces from this instant on: a later paraphrase of the
 * same idea is refused before it can be proposed.
 */
function stanceBeat(r: HtmlRejectedApproach, seq: number): Beat {
  const reason = r.reason ? `<blockquote class="human-reason">${renderInline(r.reason)}</blockquote>` : "";
  const concept = r.concept
    ? `<p class="gate-note">Recorded as the concept <code>${esc(r.concept)}</code> — a paraphrase of the same idea is caught too.</p>`
    : "";
  return beat(
    r.rejectedAt ?? "",
    seq,
    `<li class="beat beat--gate"><time>${esc(fmtTimestamp(r.rejectedAt))}</time>` +
    `<h3>${BLOCK_MARK}Rejected — and remembered: ${esc(r.description)}</h3>` +
    reason + concept +
    `<p class="gate-note">From here on the agent is blocked from proposing this again.</p></li>`,
  );
}

/** A PERSISTED preflight trace. Blocked traces render as the ⛔ callout;
 *  admitted-with-near-miss traces render the quieter "the gate weighed this"
 *  breadcrumb. Nothing is synthesized — a session with no persisted traces
 *  produces no beats here. */
function traceBeat(t: HtmlPreflightTrace, seq: number): Beat | null {
  if (t.decision === "blocked" && t.block) {
    const reason = t.block.reason ? `<blockquote class="human-reason">${renderInline(t.block.reason)}</blockquote>` : "";
    return beat(
      t.at ?? "",
      seq,
      `<li class="beat beat--gate"><time>${esc(fmtTimestamp(t.at))}</time>` +
      `<h3>${BLOCK_MARK}The gate refused ${esc(t.toolName ?? "a proposal")}</h3>` +
      `<p>It matched a stance the human had already recorded${t.block.concept ? `: <code>${esc(t.block.concept)}</code>` : ""}.</p>` +
      reason + `<p class="gate-note">Source: ${esc(t.block.source ?? "session")} memory. The artifact was never created.</p></li>`,
    );
  }
  const near = (t.nearMisses ?? []).filter((n) => n?.concept);
  if (near.length === 0) return null;
  return beat(
    t.at ?? "",
    seq,
    `<li class="beat beat--near"><time>${esc(fmtTimestamp(t.at))}</time>` +
    `<span class="beat-line">The gate weighed ${plural(t.consideredCount ?? 0, "recorded stance")} before this and let it through — ` +
    `nearest call: ${near.map((n) => `<code>${esc(n.concept)}</code>`).join(", ")}.</span></li>`,
  );
}

/** A guardrail hook ask (`hooks-state.json`). Project-scoped and path-free by
 *  design — the record carries only `at`, `hook`, `reason` — so the beat says
 *  exactly that much and no more. */
function guardrailBeat(f: HtmlGuardrailFire, seq: number): Beat {
  const category = String(f.reason ?? "").startsWith("guardrail:")
    ? String(f.reason).slice("guardrail:".length)
    : "";
  const what = category
    ? `the agent was about to touch <strong>${esc(category)}</strong> work`
    : `the agent hit the ${esc(f.hook ?? "preflight")} hook (<code>${esc(f.reason ?? "blocked")}</code>)`;
  return beat(
    f.at ?? "",
    seq,
    `<li class="beat beat--guardrail"><time>${esc(fmtTimestamp(f.at))}</time>` +
    `<h3>${SHIELD_MARK}Guardrail ask</h3>` +
    `<p>The hook stopped the run because ${what} — the human had to confirm before it continued.</p></li>`,
  );
}

// --- Story ------------------------------------------------------------------

function sessionTitle(state: HtmlSessionState): string {
  const liveDecision = state.decisions.find((d) => {
    const owner = state.artifacts.find((a) => a.id === d.artifactId);
    return !owner || !NOT_SHIPPED.has(owner.status);
  });
  if (liveDecision) return liveDecision.title?.trim() || liveDecision.context;
  const anchorTypes = ["spec", "research", "debrief", "plan", "changeset"];
  for (const type of anchorTypes) {
    const hit = state.artifacts.find((a) => a.type === type && !NOT_SHIPPED.has(a.status));
    if (hit?.title) return hit.title;
  }
  return `Session ${state.sessionId}`;
}

/** The fallback story when the agent supplied no narrative: counts, the
 *  decisions and how they landed, and the span the session covers. Labelled as
 *  auto-generated so nobody mistakes it for someone's writing. */
function autoSummary(state: HtmlSessionState, span: { first?: string; last?: string }): string {
  const byType = new Map<string, number>();
  for (const a of state.artifacts) byType.set(a.type, (byType.get(a.type) ?? 0) + 1);
  const typeList = Array.from(byType.entries())
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([t, n]) => `${n} ${esc(t)}${n === 1 ? "" : "s"}`)
    .join(", ");
  const resolved = state.decisions.filter((d) => d.response);
  const decisionList = resolved.length
    ? `<ul>${resolved
        .map((d) => {
          const chosen = d.options?.find?.((o) => o.id === d.response?.optionId);
          return `<li><strong>${esc(d.title?.trim() || d.context)}</strong> → ${esc(chosen?.title ?? d.response?.optionId ?? "")}` +
            (d.response?.reasoning ? ` — “${esc(d.response.reasoning)}”` : "") + `</li>`;
        })
        .join("")}</ul>`
    : `<p>No fork was put to the human in this session.</p>`;
  const spanLine = span.first
    ? `<p>The session runs from ${esc(fmtTimestamp(span.first))} to ${esc(fmtTimestamp(span.last))}.</p>`
    : "";
  const stances = state.sessionMemory?.rejectedApproaches ?? [];
  const stanceLine = stances.length
    ? `<p>${plural(stances.length, "approach was", "approaches were")} rejected and recorded — the gate blocks them from being re-proposed.</p>`
    : "";
  return (
    `<p class="auto-note">Auto-generated summary — no narrative was written for this export.</p>` +
    `<p>This session produced ${typeList || "no artifacts"}, ` +
    `${plural(state.comments.length, "comment")} and ${plural(resolved.length, "resolved decision")}.</p>` +
    spanLine + `<h3>Decisions</h3>` + decisionList + stanceLine
  );
}

// --- Stylesheet -------------------------------------------------------------
//
// Inline, token-driven, both color schemes, printable. No fonts are fetched —
// the stack is system-only so the page is genuinely request-free.

const STYLES = `
:root {
  color-scheme: light dark;
  --bg: #ffffff; --surface: #f7f8fa; --surface-2: #eef0f4; --border: #d8dce4;
  --text: #14181f; --muted: #5a6373; --accent: #2f6feb; --accent-soft: #e6efff;
  --ok: #1a7f4b; --bad: #b42318; --warn: #a05a00; --warn-soft: #fff4e0;
  --add-bg: #e6f6ec; --del-bg: #fdecea; --code-bg: #f4f5f8;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #0f1216; --surface: #161a21; --surface-2: #1d222b; --border: #2b323d;
    --text: #e6e9ef; --muted: #9aa4b5; --accent: #6aa0ff; --accent-soft: #16233a;
    --ok: #4cc38a; --bad: #f2726a; --warn: #e0a458; --warn-soft: #2a2115;
    --add-bg: #10291c; --del-bg: #2d1614; --code-bg: #12161c;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0; background: var(--bg); color: var(--text);
  font: 15px/1.65 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
}
.page { max-width: 62rem; margin: 0 auto; padding: 2.5rem 1.25rem 4rem; }
h1 { font-size: 1.9rem; line-height: 1.25; margin: .2rem 0 .6rem; }
h2 { font-size: 1.3rem; margin: 2.4rem 0 .8rem; padding-bottom: .35rem; border-bottom: 1px solid var(--border); }
h3 { font-size: 1.07rem; margin: .2rem 0 .5rem; }
h4 { font-size: .96rem; margin: 1rem 0 .35rem; }
p { margin: .5rem 0; }
a { color: var(--accent); }
code { font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace; font-size: .86em;
  background: var(--code-bg); padding: .08em .34em; border-radius: 4px; }
.masthead { border-bottom: 2px solid var(--border); padding-bottom: 1.1rem; }
.eyebrow { text-transform: uppercase; letter-spacing: .09em; font-size: .7rem; color: var(--muted); margin: 0; }
.meta { display: flex; flex-wrap: wrap; gap: .4rem .9rem; font-size: .8rem; color: var(--muted); margin: .5rem 0 0; }
.meta span { white-space: nowrap; }
.audience { font-size: .85rem; color: var(--muted); font-style: italic; }
.story { background: var(--surface); border: 1px solid var(--border); border-radius: 10px;
  padding: 1.1rem 1.3rem; margin-top: 1.4rem; }
.story h2 { margin-top: 0; border: 0; }
.auto-note { font-size: .8rem; color: var(--muted); font-style: italic; }
.beats { list-style: none; margin: 0; padding: 0; }
.beat { border-left: 2px solid var(--border); margin: 0 0 1.1rem; padding: .2rem 0 .2rem 1.1rem; position: relative; }
.beat > time, .beat-head time { display: inline-block; font-size: .74rem; color: var(--muted); letter-spacing: .02em; }
.beat--artifact { border-left-color: var(--accent); background: var(--surface);
  border: 1px solid var(--border); border-left: 3px solid var(--accent);
  border-radius: 10px; padding: .9rem 1.1rem; }
.beat--not-shipped { border-left-color: var(--bad); opacity: .92; }
.beat--gate { border-left: 3px solid var(--bad); background: var(--surface); border-radius: 10px;
  padding: .8rem 1.1rem; border-top: 1px solid var(--border); border-right: 1px solid var(--border);
  border-bottom: 1px solid var(--border); }
.beat--guardrail { border-left: 3px solid var(--warn); background: var(--warn-soft); border-radius: 10px; padding: .8rem 1.1rem; }
.beat--near { border-left-color: var(--warn); }
.beat--decided { border-left: 3px solid var(--ok); background: var(--surface); border-radius: 10px;
  padding: .8rem 1.1rem; border-top: 1px solid var(--border); border-right: 1px solid var(--border);
  border-bottom: 1px solid var(--border); }
.beat--ok { border-left-color: var(--ok); }
.beat--bad { border-left-color: var(--bad); }
.beat-line { display: block; font-size: .9rem; }
.gate-mark { display: inline-flex; vertical-align: -.16em; margin-right: .4rem; color: var(--bad); }
.beat--guardrail .gate-mark { color: var(--warn); }
.gate-note { font-size: .82rem; color: var(--muted); }
.chips { display: flex; flex-wrap: wrap; gap: .3rem; margin: .35rem 0; }
.chip { display: inline-block; font-size: .68rem; text-transform: uppercase; letter-spacing: .05em;
  background: var(--surface-2); color: var(--muted); border: 1px solid var(--border);
  border-radius: 999px; padding: .08rem .5rem; margin-left: .35rem; white-space: nowrap; }
.chip--chosen { background: var(--ok); color: #fff; border-color: transparent; }
.chip--sig-high, .chip--sev-high, .chip--sev-critical { background: var(--bad); color: #fff; border-color: transparent; }
.chip--question { background: var(--accent-soft); color: var(--accent); }
.verdict { font-size: .86rem; padding: .45rem .7rem; border-radius: 6px; margin: .4rem 0; }
.verdict--rejected { background: var(--del-bg); color: var(--bad); }
.verdict--superseded { background: var(--surface-2); color: var(--muted); }
.verdict--chosen { background: var(--add-bg); color: var(--ok); }
.human-reason { margin: .5rem 0; padding: .35rem 0 .35rem .8rem; border-left: 3px solid var(--accent);
  color: var(--text); font-style: italic; }
.kv .k, p.k { font-weight: 600; color: var(--muted); font-size: .78rem; text-transform: uppercase; letter-spacing: .05em; }
.why { color: var(--muted); font-size: .9rem; }
.finding { border-top: 1px solid var(--border); padding-top: .7rem; margin-top: .7rem; }
.evidence { margin: .5rem 0; }
.anchor { margin: .3rem 0 .2rem; font-size: .8rem; }
.evidence-note { font-size: .88rem; color: var(--muted); }
pre.code { background: var(--code-bg); border: 1px solid var(--border); border-radius: 8px;
  padding: .7rem .85rem; overflow-x: auto; font-size: .8rem; line-height: 1.5; margin: .4rem 0; }
pre.code code { background: none; padding: 0; font-size: inherit; }
.code-label { font-size: .74rem; text-transform: uppercase; letter-spacing: .05em; color: var(--muted); margin: .5rem 0 .1rem; }
.truncated { display: block; color: var(--muted); font-style: italic; }
.redacted { font-size: .82rem; color: var(--muted); font-style: italic;
  background: var(--surface-2); border: 1px dashed var(--border); border-radius: 6px; padding: .4rem .6rem; }
.file { border: 1px solid var(--border); border-radius: 8px; overflow: hidden; margin: .7rem 0; }
.file-head { background: var(--surface-2); padding: .4rem .7rem; display: flex; flex-wrap: wrap;
  align-items: center; gap: .4rem; font-size: .85rem; }
.file-head .path { background: none; padding: 0; word-break: break-all; }
.diffstat { font-size: .75rem; margin-left: auto; }
.diffstat .add { color: var(--ok); } .diffstat .del { color: var(--bad); }
.diff { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: .78rem;
  line-height: 1.5; overflow-x: auto; }
.dl { display: flex; white-space: pre; }
.dl--add { background: var(--add-bg); } .dl--del { background: var(--del-bg); }
.dl--hunk { color: var(--muted); background: var(--surface-2); padding: .1rem .7rem; }
.dl--trunc { color: var(--muted); font-style: italic; padding: .2rem .7rem; white-space: normal; }
.ln { flex: 0 0 3.2rem; text-align: right; padding-right: .6rem; color: var(--muted); user-select: none; }
.sign { flex: 0 0 1rem; color: var(--muted); }
.src { flex: 1 1 auto; padding-right: .7rem; }
details { margin: .4rem 0; }
summary { cursor: pointer; font-size: .82rem; color: var(--accent); padding: .2rem 0; }
.thread { margin-top: .8rem; border-top: 1px dashed var(--border); padding-top: .5rem; }
.thread-head { font-size: .78rem; text-transform: uppercase; letter-spacing: .05em; color: var(--muted); margin: 0 0 .3rem; }
.thread-list { list-style: none; margin: 0; padding: 0; }
.thread-item { background: var(--surface-2); border-radius: 8px; padding: .5rem .7rem; margin: .35rem 0; }
.thread-item--agent { background: var(--surface); border: 1px solid var(--border); }
.thread-meta { display: flex; flex-wrap: wrap; align-items: center; gap: .4rem; font-size: .74rem; color: var(--muted); }
.thread-meta .who { font-weight: 600; color: var(--text); }
.thread-anchor { font-style: italic; }
.thread-body p { margin: .25rem 0; font-size: .92rem; }
.option { border: 1px solid var(--border); border-radius: 8px; padding: .6rem .8rem; margin: .5rem 0; }
.option--chosen { border-color: var(--ok); background: var(--add-bg); }
.option-head { display: flex; align-items: center; gap: .4rem; flex-wrap: wrap; }
.option-head h4 { margin: 0; }
.pros li::marker { color: var(--ok); } .cons li::marker { color: var(--bad); }
.needs-eyes { background: var(--warn-soft); border: 1px solid var(--border); border-radius: 8px; padding: .5rem .8rem; }
.req-list, .steps { padding-left: 1.2rem; }
.req-head { display: flex; align-items: center; gap: .4rem; }
.open-question { color: var(--muted); font-style: italic; }
.stances li { margin: .4rem 0; }
footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border);
  font-size: .8rem; color: var(--muted); display: flex; flex-wrap: wrap; gap: .5rem 1rem; }
@media (max-width: 640px) {
  .page { padding: 1.5rem .8rem 3rem; }
  .ln { flex-basis: 2.2rem; }
}
@media print {
  body { background: #fff; color: #000; }
  .beat, .beat--artifact, .story { break-inside: avoid; }
  details { display: block; }
  details > summary { display: none; }
  details > *:not(summary) { display: block !important; }
  a::after { content: " (" attr(href) ")"; font-size: .7em; color: #555; }
}
`;

// --- The page ---------------------------------------------------------------

export function formatSessionHtml(state: HtmlSessionState, options: HtmlExportOptions = {}): string {
  const includeCode = options.includeCode !== false;
  const generatedAt = options.generatedAt ?? new Date().toISOString();
  const version = options.version ?? "";
  const projectName = options.projectName ?? "";
  const projectRoot = options.projectRoot;

  const artifactIds = new Set(state.artifacts.map((a) => a.id));
  const commentsByArtifact = new Map<string, Comment[]>();
  const looseComments: Comment[] = [];
  for (const c of state.comments ?? []) {
    const id = c.target?.artifactId;
    if (id && artifactIds.has(id)) {
      const list = commentsByArtifact.get(id) ?? [];
      list.push(c);
      commentsByArtifact.set(id, list);
    } else {
      looseComments.push(c);
    }
  }

  const ctx: RenderCtx = { state, includeCode, projectRoot, commentsByArtifact };

  const events = buildTimeline({
    artifacts: state.artifacts,
    comments: state.comments,
    decisions: state.decisions as DecisionRecord[],
    planReviews: state.planReviews as PlanReviewRecord[],
  });

  const artifactById = new Map(state.artifacts.map((a) => [a.id, a]));
  const beats: Beat[] = [];
  let seq = 0;

  for (const event of events) {
    switch (event.kind) {
      case "artifact_created": {
        const a = event.artifactId ? artifactById.get(event.artifactId) : undefined;
        if (a) beats.push(artifactBeat(a, ctx, seq++));
        break;
      }
      case "artifact_status_changed":
        beats.push(statusBeat(event, seq++));
        break;
      case "decision_resolved":
        beats.push(decisionBeat(event, seq++));
        break;
      case "plan_reviewed":
        beats.push(planReviewBeat(event, seq++));
        break;
      case "comment_added":
        // Comments on an artifact render INSIDE that artifact's card (anchored
        // where they happened); only session-level comments become beats.
        break;
      default:
        break;
    }
  }

  for (const c of looseComments) beats.push(looseCommentBeat(c, ctx, seq++));

  const stances = state.sessionMemory?.rejectedApproaches ?? [];
  const timedStances = stances.filter((r) => !!r.rejectedAt);
  const untimedStances = stances.filter((r) => !r.rejectedAt);
  for (const r of timedStances) beats.push(stanceBeat(r, seq++));

  for (const t of state.preflightTraces ?? []) {
    const b = traceBeat(t, seq++);
    if (b) beats.push(b);
  }

  // Guardrail fires are PROJECT-scoped (hooks-state.json has no session id), so
  // only the ones inside this session's own window can honestly be claimed as
  // part of this story.
  const stamps = beats.map((b) => b.at).filter(Boolean).sort();
  const spanFirst = stamps[0];
  const spanLast = stamps[stamps.length - 1];
  for (const f of state.guardrailFires ?? []) {
    if (!f.at) continue;
    if (spanFirst && f.at < spanFirst) continue;
    if (spanLast && f.at > spanLast) continue;
    beats.push(guardrailBeat(f, seq++));
  }

  beats.sort((a, b) => {
    if (a.at && b.at && a.at !== b.at) return a.at.localeCompare(b.at);
    if (!a.at && b.at) return 1;
    if (a.at && !b.at) return -1;
    return a.seq - b.seq;
  });

  const allStamps = beats.map((b) => b.at).filter(Boolean).sort();
  const span = { first: allStamps[0], last: allStamps[allStamps.length - 1] };

  const title = sessionTitle(state);
  const story = options.narrative?.trim()
    ? renderMarkdown(options.narrative, 3)
    : autoSummary(state, span);

  const metaBits = [
    projectName ? `<span>Project: ${esc(projectName)}</span>` : "",
    `<span>Session: <code>${esc(state.sessionId)}</code></span>`,
    span.first ? `<span>${esc(fmtDay(span.first))} → ${esc(fmtDay(span.last))}</span>` : "",
    `<span>Exported ${esc(fmtDay(generatedAt))}</span>`,
    version ? `<span>deepPairing v${esc(version)}</span>` : "",
    includeCode ? "" : `<span>code omitted</span>`,
  ].filter(Boolean).join("");

  const audienceLine = options.audience?.trim()
    ? `<p class="audience">Written for ${esc(options.audience.trim())}.</p>`
    : "";

  const timeline = beats.length
    ? `<ol class="beats">${beats.map((b) => b.html).join("")}</ol>`
    : `<p class="open-question">Nothing was recorded in this session.</p>`;

  const stancesSection = untimedStances.length
    ? `<section><h2>Standing stances</h2>` +
      `<p>Recorded without a timestamp, so they can't be placed on the timeline — but the gate enforces them all the same.</p>` +
      `<ul class="stances">${untimedStances
        .map((r) => `<li><strong>${esc(r.description)}</strong>${r.reason ? ` — “${esc(r.reason)}”` : ""}${r.concept ? ` <code>${esc(r.concept)}</code>` : ""}</li>`)
        .join("")}</ul></section>`
    : "";

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="color-scheme" content="light dark" />
<meta name="generator" content="deepPairing${version ? ` ${esc(version)}` : ""}" />
<title>${esc(title)} — deepPairing session</title>
<style>${STYLES}</style>
</head>
<body>
<main class="page">
<header class="masthead">
<p class="eyebrow">deepPairing session</p>
<h1>${esc(title)}</h1>
${audienceLine}
<div class="meta">${metaBits}</div>
</header>

<section class="story">
<h2>What this was</h2>
${story}
</section>

<section class="timeline">
<h2>How it unfolded</h2>
${timeline}
</section>

${stancesSection}

<footer>
<span>Generated by deepPairing${version ? ` v${esc(version)}` : ""} — ${esc(fmtTimestamp(generatedAt))}</span>
<span><a href="${REPO_URL}" rel="noopener noreferrer">github.com/mitchjablonski/deepPairing</a></span>
</footer>
</main>
</body>
</html>
`;
}
