import type { Artifact, Comment, SessionAnnotation } from "@deeppairing/shared";
import { buildTimeline } from "../replay/timeline.js";
import type { DecisionRecord, PlanReviewRecord } from "../store/store-interface.js";
import {
  normalizeConceptKey,
  coercePlanContent,
  coerceResearchContent,
  coerceReasoningContent,
} from "@deeppairing/shared";

interface SessionState {
  sessionId: string;
  artifacts: Artifact[];
  comments: Comment[];
  decisions: Array<{
    decisionId: string;
    artifactId: string;
    context: string;
    options: any[];
    response?: { optionId: string; reasoning?: string };
    createdAt: string;
    resolvedAt?: string;
  }>;
  planReviews: Array<{
    artifactId: string;
    verdict?: string;
    feedback?: string;
    createdAt?: string;
    resolvedAt?: string;
  }>;
  /** Optional — attached by callers who want annotations in the replay export. */
  annotations?: SessionAnnotation[];
}

type ExportFormat = "full" | "pr-description" | "adr" | "replay" | "pr-comments" | "learnings";

export function formatSessionMarkdown(
  state: SessionState,
  format: ExportFormat = "full",
): string {
  switch (format) {
    case "pr-description":
      return formatPrDescription(state);
    case "adr":
      return formatAdr(state);
    case "replay":
      return formatReplay(state);
    case "pr-comments":
      return formatPrComments(state);
    case "learnings":
      return formatLearnings(state);
    case "full":
    default:
      return formatFull(state);
  }
}

// --- PR Description ---

function formatPrDescription(state: SessionState): string {
  const sections: string[] = [];

  sections.push("## Summary\n");

  // Decisions made
  const resolved = state.decisions.filter((d) => d.response);
  if (resolved.length > 0) {
    sections.push("### Decisions\n");
    for (const d of resolved) {
      const option = d.options.find((o: any) => o.id === d.response?.optionId);
      sections.push(`- **${d.context}**: ${option?.title ?? d.response?.optionId}`);
      if (d.response?.reasoning) {
        sections.push(`  - *Reasoning*: ${d.response.reasoning}`);
      }
    }
    sections.push("");
  }

  // Plan steps
  const plans = state.artifacts.filter((a) => a.type === "plan" && a.status !== "superseded");
  for (const plan of plans) {
    const steps = coercePlanContent(plan.content).steps;
    if (steps.length > 0) {
      sections.push(`### Changes (${plan.title})\n`);
      for (const step of steps) {
        const files = Array.isArray(step.files)
          ? step.files.map((f: any) => typeof f === "string" ? f : f.filePath).join(", ")
          : "";
        sections.push(`- ${step.description}${files ? ` (${files})` : ""}`);
      }
      sections.push("");
    }
  }

  // Key findings
  const research = state.artifacts.filter((a) => a.type === "research" && a.status !== "superseded");
  if (research.length > 0) {
    const findings = research.flatMap((r) => coerceResearchContent(r.content).findings);
    const highFindings = findings.filter((f: any) => f.significance === "high");
    if (highFindings.length > 0) {
      sections.push("### Key Findings\n");
      for (const f of highFindings) {
        sections.push(`- **${f.title ?? f.category}**: ${f.detail}`);
      }
      sections.push("");
    }
  }

  sections.push("\n---\n*Generated by [deepPairing](https://github.com/deeppairing)*");

  return sections.join("\n");
}

// --- Architecture Decision Record ---

function formatAdr(state: SessionState): string {
  const sections: string[] = [];
  const date = new Date().toISOString().split("T")[0];

  sections.push(`# ADR: ${getSessionTitle(state)}\n`);
  sections.push(`**Date**: ${date}`);
  sections.push(`**Status**: Accepted\n`);

  // Context — from findings
  const research = state.artifacts.filter((a) => a.type === "research" && a.status !== "superseded");
  if (research.length > 0) {
    sections.push("## Context\n");
    for (const r of research) {
      const content = coerceResearchContent(r.content);
      if (content.summary) sections.push(content.summary + "\n");
      for (const f of content.findings ?? []) {
        sections.push(`### ${f.title ?? f.category}\n`);
        sections.push(f.detail);
        if (f.impact) sections.push(`\n**Impact**: ${f.impact}`);
        sections.push("");
      }
    }
  }

  // Decision — from resolved decisions
  const resolved = state.decisions.filter((d) => d.response);
  if (resolved.length > 0) {
    sections.push("## Decision\n");
    for (const d of resolved) {
      const chosen = d.options.find((o: any) => o.id === d.response?.optionId);
      const rejected = d.options.filter((o: any) => o.id !== d.response?.optionId);

      sections.push(`**${d.context}**\n`);
      sections.push(`Chosen: **${chosen?.title}** — ${chosen?.description ?? ""}`);
      if (d.response?.reasoning) {
        sections.push(`\nReasoning: ${d.response.reasoning}`);
      }
      if (rejected.length > 0) {
        sections.push("\nRejected alternatives:");
        for (const r of rejected) {
          sections.push(`- ${r.title}: ${r.description ?? ""}`);
        }
      }
      sections.push("");
    }
  }

  // Consequences — from plan
  const plans = state.artifacts.filter((a) => a.type === "plan" && a.status !== "superseded");
  if (plans.length > 0) {
    sections.push("## Consequences\n");
    for (const plan of plans) {
      for (const step of coercePlanContent(plan.content).steps) {
        sections.push(`- ${step.description}: ${step.reasoning}`);
      }
    }
    sections.push("");
  }

  return sections.join("\n");
}

// --- Full Export ---

function formatFull(state: SessionState): string {
  const sections: string[] = [];

  sections.push(`# deepPairing Session Report\n`);
  sections.push(`**Session**: ${state.sessionId}`);
  sections.push(`**Date**: ${new Date().toISOString().split("T")[0]}\n`);
  sections.push("---\n");

  // Research findings
  const research = state.artifacts.filter((a) => a.type === "research" && a.status !== "superseded");
  if (research.length > 0) {
    sections.push("## Findings\n");
    for (const r of research) {
      const content = coerceResearchContent(r.content);
      if (content.summary) sections.push(`${content.summary}\n`);

      for (const f of content.findings ?? []) {
        sections.push(`### ${f.title ?? f.category} (${f.significance})\n`);
        sections.push(f.detail + "\n");

        // Evidence with code. D7 — the typed coercer surfaced what the old
        // `as any` hid: evidence ARRAYS can still contain plain strings
        // (legacy mixed shape); narrow per element instead of assuming objects.
        if (Array.isArray(f.evidence)) {
          for (const ev of f.evidence) {
            if (typeof ev === "string") {
              sections.push(`> ${ev}`);
              sections.push("");
              continue;
            }
            sections.push(`\`${ev.filePath}:${ev.lineStart}-${ev.lineEnd}\``);
            if (ev.snippet) {
              sections.push("```" + (ev.language ?? ""));
              sections.push(ev.snippet);
              sections.push("```");
            }
            if (ev.explanation) sections.push(`> ${ev.explanation}`);
            sections.push("");
          }
        } else if (typeof f.evidence === "string") {
          sections.push(`Evidence: ${f.evidence}\n`);
        }

        if (f.impact) sections.push(`**Impact**: ${f.impact}\n`);
        if (f.recommendation) sections.push(`**Recommendation**: ${f.recommendation}\n`);
      }

      // Comments on this artifact
      const artComments = state.comments.filter((c) => c.target.artifactId === r.id);
      if (artComments.length > 0) {
        sections.push("**Comments:**");
        for (const c of artComments) {
          sections.push(`- *${c.author}*: ${c.content}`);
        }
        sections.push("");
      }
    }
  }

  // Decisions
  const resolved = state.decisions.filter((d) => d.response);
  if (resolved.length > 0) {
    sections.push("## Decisions\n");
    for (const d of resolved) {
      const chosen = d.options.find((o: any) => o.id === d.response?.optionId);
      sections.push(`### ${d.context}\n`);
      sections.push(`**Selected**: ${chosen?.title ?? d.response?.optionId}`);
      if (d.response?.reasoning) sections.push(`**Reasoning**: ${d.response.reasoning}`);
      sections.push("\nOptions considered:");
      for (const o of d.options) {
        const marker = o.id === d.response?.optionId ? "✓" : "✗";
        sections.push(`- ${marker} **${o.title}** (${o.effort} effort, ${o.risk} risk): ${o.description ?? ""}`);
      }
      sections.push("");
    }
  }

  // Plans
  const plans = state.artifacts.filter((a) => a.type === "plan" && a.status !== "superseded");
  if (plans.length > 0) {
    sections.push("## Implementation Plan\n");
    for (const plan of plans) {
      sections.push(`### ${plan.title}\n`);
      const review = state.planReviews.find((p) => p.artifactId === plan.id);
      if (review?.verdict) sections.push(`**Status**: ${review.verdict}\n`);

      for (const [i, step] of coercePlanContent(plan.content).steps.entries()) {
        sections.push(`${i + 1}. **${step.description}** — ${step.reasoning}`);
        if (step.motivatedBy?.length) {
          sections.push(`   *Motivated by*: ${step.motivatedBy.join(", ")}`);
        }
      }
      sections.push("");
    }
  }

  // Reasoning log
  const reasoning = state.artifacts.filter((a) => a.type === "reasoning");
  if (reasoning.length > 0) {
    sections.push("<details><summary>Reasoning Log</summary>\n");
    for (const r of reasoning) {
      const content = coerceReasoningContent(r.content);
      sections.push(`- **${content.action}** (${content.confidence}): ${content.reasoning}`);
    }
    sections.push("\n</details>\n");
  }

  sections.push("---\n*Generated by [deepPairing](https://github.com/deeppairing)*");

  return sections.join("\n");
}

function getSessionTitle(state: SessionState): string {
  const firstDecision = state.decisions[0];
  if (firstDecision) return firstDecision.context;
  const firstResearch = state.artifacts.find((a) => a.type === "research");
  if (firstResearch) return firstResearch.title;
  return "Session " + state.sessionId;
}

// --- Replay format (chronological narrative for learning re-reads) ---

function formatReplay(state: SessionState): string {
  const title = getSessionTitle(state);
  const sections: string[] = [];

  sections.push(`# Replay: ${title}\n`);
  sections.push(`*Chronological walkthrough for learning re-read.*\n`);

  const events = buildTimeline({
    artifacts: state.artifacts,
    comments: state.comments,
    decisions: state.decisions as DecisionRecord[],
    planReviews: state.planReviews as PlanReviewRecord[],
  });

  // Group annotations by target event for inline marginalia.
  const annotationsByEvent = new Map<string, SessionAnnotation[]>();
  for (const ann of state.annotations ?? []) {
    const list = annotationsByEvent.get(ann.targetEventId) ?? [];
    list.push(ann);
    annotationsByEvent.set(ann.targetEventId, list);
  }

  if (events.length === 0) {
    sections.push("_No events recorded in this session._");
    return sections.join("\n");
  }

  sections.push("## Timeline\n");
  for (const event of events) {
    const when = formatTime(event.at);
    const icon = replayIcon(event.kind);
    sections.push(`### ${icon} ${when} — ${event.label}`);

    // Kind-specific body
    if (event.kind === "decision_resolved") {
      const p = event.payload ?? {};
      if (p.reasoning) sections.push(`Reasoning: ${p.reasoning}`);
      if (Array.isArray(p.rejectedTitles) && p.rejectedTitles.length > 0) {
        sections.push(`_Rejected:_ ${(p.rejectedTitles as string[]).join(", ")}`);
      }
    } else if (event.kind === "comment_added") {
      const p = event.payload ?? {};
      const who = p.author === "agent" ? "Agent" : p.intent === "question" ? "You asked" : "You";
      sections.push(`${who}: ${p.content}`);
    } else if (event.kind === "plan_reviewed") {
      const p = event.payload ?? {};
      if (p.feedback) sections.push(`Feedback: ${p.feedback}`);
    }

    // Learner annotations attached to this event
    const anns = annotationsByEvent.get(event.id);
    if (anns && anns.length > 0) {
      for (const ann of anns) {
        sections.push(`> 📝 **note:** ${ann.note}${ann.tags?.length ? ` \`[${ann.tags.join(", ")}]\`` : ""}`);
      }
    }
    sections.push("");
  }

  sections.push("---\n*Generated by [deepPairing](https://github.com/deeppairing)*");
  return sections.join("\n");
}

function replayIcon(kind: string): string {
  switch (kind) {
    case "artifact_created": return "➕";
    case "artifact_status_changed": return "🔄";
    case "comment_added": return "💬";
    case "decision_resolved": return "⚖️";
    case "plan_reviewed": return "📋";
    default: return "•";
  }
}

function formatTime(iso: string): string {
  try {
    const d = new Date(iso);
    return d.toISOString().replace("T", " ").slice(0, 19);
  } catch {
    return iso;
  }
}

const severityEmoji: Record<string, string> = {
  critical: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "🟢",
  info: "⚪",
};

// --- GitHub PR review API payload ---
//
// Shape matches POST /repos/{owner}/{repo}/pulls/{pull_number}/reviews so
// we can shell out to `gh api ... --input -` with this object as stdin.
// https://docs.github.com/en/rest/pulls/reviews

export type GitHubReviewEvent = "COMMENT" | "REQUEST_CHANGES" | "APPROVE";

export interface GitHubReviewComment {
  path: string;
  line: number;
  side: "RIGHT" | "LEFT";
  body: string;
}

export interface GitHubReviewPayload {
  body: string;
  event: GitHubReviewEvent;
  comments: GitHubReviewComment[];
}

/**
 * Build the GitHub "review with inline comments" payload from a session.
 * One comment per distinct evidence location in an approved research
 * artifact; severity chip + explanation + impact + recommendation compose
 * the comment body. A top-level body summarizes the session.
 *
 * Rejected / retracted / superseded research artifacts are omitted — the
 * user didn't want those going to a PR.
 */
export function buildGitHubReviewPayload(
  state: SessionState,
  opts: { event?: GitHubReviewEvent } = {},
): GitHubReviewPayload {
  const comments: GitHubReviewComment[] = [];
  const findingTitles: string[] = [];

  const researchArtifacts = state.artifacts.filter(
    (a) => a.type === "research" &&
      a.status !== "rejected" && a.status !== "retracted" && a.status !== "superseded",
  );

  for (const artifact of researchArtifacts) {
    const findings = coerceResearchContent(artifact.content).findings;
    if (!Array.isArray(findings)) continue;

    for (const finding of findings) {
      const evidence = Array.isArray(finding.evidence) ? finding.evidence : [];
      // D7 — the runtime narrowing existed; the predicate is now a TYPE guard
      // so the loop below reads typed evidence instead of any.
      const structured = evidence.filter(
        (e): e is Exclude<typeof e, string> =>
          !!e && typeof e === "object" && !!e.filePath && typeof e.lineStart === "number",
      );
      if (structured.length === 0) continue;

      const sev = finding.severity ?? "info";
      const chip = severityEmoji[sev] ?? "⚪";
      const title = finding.title ? `**${finding.title}**` : `**${finding.category ?? "Finding"}**`;
      if (finding.title) findingTitles.push(finding.title);

      for (const ev of structured) {
        const bodyLines: string[] = [];
        bodyLines.push(`${chip} ${title} — ${sev.toUpperCase()}${finding.category ? ` · ${finding.category}` : ""}`);
        if (finding.detail) {
          bodyLines.push("");
          bodyLines.push(finding.detail);
        }
        if (ev.explanation) {
          bodyLines.push("");
          bodyLines.push(`_${ev.explanation}_`);
        }
        if (finding.impact) {
          bodyLines.push("");
          bodyLines.push(`**Impact:** ${finding.impact}`);
        }
        if (finding.recommendation) {
          bodyLines.push("");
          bodyLines.push(`**Recommendation:** ${finding.recommendation}`);
        }

        comments.push({
          path: ev.filePath,
          // GitHub's review API uses the END line for multi-line comments
          // (set via start_line/line pair in the richer endpoint). For the
          // simple single-line shape, anchor to lineEnd when it exists.
          line: ev.lineEnd ?? ev.lineStart,
          side: "RIGHT",
          body: bodyLines.join("\n"),
        });
      }
    }
  }

  const title = getSessionTitle(state);
  const bodyParts: string[] = [
    `## deepPairing notes — ${title}`,
    "",
  ];
  if (comments.length === 0) {
    bodyParts.push("_No reviewable findings with structured evidence in this pairing session._");
  } else {
    bodyParts.push(`${comments.length} inline comment${comments.length === 1 ? "" : "s"} from this pairing session.`);
    if (findingTitles.length > 0) {
      bodyParts.push("");
      bodyParts.push("**Findings:**");
      for (const t of findingTitles) bodyParts.push(`- ${t}`);
    }
  }
  bodyParts.push("");
  bodyParts.push(`*Generated by [deepPairing](https://github.com/deeppairing). Session: ${state.sessionId}*`);

  return {
    body: bodyParts.join("\n"),
    event: opts.event ?? "COMMENT",
    comments,
  };
}

// --- PR-comments format (pairing output formatted as inline PR comments) ---
//
// Posts the output of a pairing session onto a PR. NOT a review tool — these
// comments are the artifacts of pairing on the change together. Each surviving
// finding (with structured evidence) becomes a quoted file:line reference +
// severity chip + impact/recommendation. Rejected findings are omitted; the
// pair already decided they weren't load-bearing.

function formatPrComments(state: SessionState): string {
  const sections: string[] = [];
  const title = getSessionTitle(state);
  sections.push(`## deepPairing notes — ${title}`);
  sections.push("");

  // Only include findings that weren't rejected — a reviewer doesn't want
  // to paste their own rejected concerns.
  const researchArtifacts = state.artifacts.filter(
    (a) => a.type === "research" && a.status !== "rejected" && a.status !== "retracted" && a.status !== "superseded",
  );

  const allFindings: Array<{
    artifact: Artifact;
    finding: any;
    index: number;
  }> = [];
  for (const artifact of researchArtifacts) {
    const findings = coerceResearchContent(artifact.content).findings;
    if (!Array.isArray(findings)) continue;
    findings.forEach((f: any, i: number) => {
      allFindings.push({ artifact, finding: f, index: i });
    });
  }

  if (allFindings.length === 0) {
    sections.push("_No findings from this pairing session._");
    sections.push("");
    return sections.join("\n");
  }

  // Group by file (first file mentioned in each finding's evidence). Files
  // that don't resolve (non-structured evidence) go into a "General" bucket.
  const byFile = new Map<string, typeof allFindings>();
  for (const entry of allFindings) {
    const evidence = entry.finding.evidence;
    const firstPath = Array.isArray(evidence) && evidence[0] && typeof evidence[0] === "object"
      ? (evidence[0] as any).filePath
      : undefined;
    const key = firstPath ?? "General";
    const list = byFile.get(key) ?? [];
    list.push(entry);
    byFile.set(key, list);
  }

  for (const [filePath, entries] of byFile.entries()) {
    sections.push(`### ${filePath}`);
    sections.push("");
    for (const { finding } of entries) {
      const sev = finding.severity ?? "info";
      const chip = `${severityEmoji[sev] ?? "⚪"} **${sev.toUpperCase()}**`;
      const category = finding.category ? ` · ${finding.category}` : "";
      const title = finding.title ? ` — ${finding.title}` : "";
      sections.push(`${chip}${category}${title}`);
      sections.push("");

      // File:line anchor + snippet
      const evidenceList = Array.isArray(finding.evidence) ? finding.evidence : [];
      for (const ev of evidenceList) {
        if (typeof ev !== "object" || !ev.filePath) continue;
        const linePart = ev.lineEnd && ev.lineEnd !== ev.lineStart
          ? `L${ev.lineStart}-L${ev.lineEnd}`
          : `L${ev.lineStart}`;
        sections.push(`> \`${ev.filePath}:${linePart}\``);
        if (ev.snippet) {
          const lang = ev.language ?? "";
          sections.push("> ```" + lang);
          for (const line of ev.snippet.split("\n")) {
            sections.push("> " + line);
          }
          sections.push("> ```");
        }
        if (ev.explanation) {
          sections.push(`> ${ev.explanation}`);
        }
      }

      if (finding.detail) {
        sections.push("");
        sections.push(finding.detail);
      }
      if (finding.impact) {
        sections.push("");
        sections.push(`**Impact:** ${finding.impact}`);
      }
      if (finding.recommendation) {
        sections.push("");
        sections.push(`**Recommendation:** ${finding.recommendation}`);
      }
      sections.push("");
      sections.push("---");
      sections.push("");
    }
  }

  sections.push("*Output from a [deepPairing](https://github.com/deeppairing) session — paste into a PR comment.*");
  return sections.join("\n");
}

// --- Learnings format (R3) ---
//
// A teaching artifact: what the pair *learned* during this session, not what
// they built. Three sections:
//   - Concepts named via log_reasoning (with count per concept)
//   - Predictions captured on high-stakes decisions, cross-referenced with
//     any retrospectives (verdict + note) so the calibration loop is visible
//   - Rejected approaches with reasons — the "you won't re-propose this"
//     moat, made legible for sharing
//
// Distinct from `full` (everything) and `replay` (chronological). This is
// what you paste into a weekly learning channel or a hiring doc.

function formatLearnings(state: SessionState): string {
  const sections: string[] = [];
  const title = getSessionTitle(state);
  sections.push(`# Learnings — ${title}`);
  sections.push("");
  sections.push(
    "*Teaching artifact: concepts named, predictions made, and approaches you won't re-propose.*",
  );
  sections.push("");

  // --- Concepts named via log_reasoning ---
  const reasoningArtifacts = state.artifacts.filter(
    (a) => a.type === "reasoning" && a.status !== "superseded" && a.status !== "retracted",
  );
  const conceptCounts = new Map<string, { name: string; explanation?: string; count: number; actions: string[] }>();
  for (const a of reasoningArtifacts) {
    const concept = coerceReasoningContent(a.content).concept;
    if (!concept?.name) continue;
    const key = normalizeConceptKey(String(concept.name));
    if (!key) continue;
    const existing = conceptCounts.get(key);
    const action = coerceReasoningContent(a.content).action || null;
    if (existing) {
      existing.count += 1;
      if (action && !existing.actions.includes(action)) existing.actions.push(action);
    } else {
      conceptCounts.set(key, {
        name: String(concept.name).trim(),
        explanation: concept.oneLineExplanation ? String(concept.oneLineExplanation) : undefined,
        count: 1,
        actions: action ? [action] : [],
      });
    }
  }

  if (conceptCounts.size > 0) {
    sections.push("## Concepts the pair named");
    sections.push("");
    // Sort by count desc, then name asc so recurring patterns lead.
    const sorted = Array.from(conceptCounts.values()).sort(
      (a, b) => (b.count - a.count) || a.name.localeCompare(b.name),
    );
    for (const c of sorted) {
      const countLabel = c.count > 1 ? ` _(×${c.count})_` : "";
      sections.push(`- **${c.name}**${countLabel}`);
      if (c.explanation) sections.push(`  > ${c.explanation}`);
      if (c.actions.length > 0) {
        const shown = c.actions.slice(0, 3);
        for (const act of shown) sections.push(`  - applied to: ${act}`);
      }
    }
    sections.push("");
  }

  // --- Predictions + retrospectives ---
  const decisionsWithPredictions = state.decisions.filter(
    (d) => (d.response as any)?.predictedOutcome,
  );
  if (decisionsWithPredictions.length > 0) {
    sections.push("## Predictions captured");
    sections.push("");
    for (const d of decisionsWithPredictions) {
      const chosen = d.options.find((o: any) => o.id === d.response?.optionId);
      const confidence = (d.response as any)?.confidence;
      sections.push(
        `- **${d.context}**: chose _${chosen?.title ?? d.response?.optionId}_${
          confidence ? ` (${confidence} confidence)` : ""
        }`,
      );
      sections.push(`  - Predicted: "${(d.response as any).predictedOutcome}"`);
      const retro = findRetrospective(state, d.decisionId);
      if (retro) {
        const mark = retro.verdict === "right" ? "✓" : retro.verdict === "wrong" ? "✗" : "◐";
        sections.push(`  - Looking back: ${mark} ${retro.verdict}${retro.note ? ` — "${retro.note}"` : ""}`);
      }
    }
    sections.push("");
  }

  // --- Rejected approaches ---
  // We pull these from the state's session metadata when available; otherwise
  // we reconstruct from rejected-status artifacts with a reason.
  const rejectedFromStatus = state.artifacts.filter(
    (a) => a.status === "rejected" && a.type !== "reasoning",
  );
  const rejectedApproaches = (state as any).sessionMemory?.rejectedApproaches as
    | Array<{ description: string; reason?: string; concept?: string }>
    | undefined;

  const seenReasons = new Set<string>();
  const rows: string[] = [];
  if (rejectedApproaches) {
    for (const r of rejectedApproaches) {
      const key = r.description;
      if (seenReasons.has(key)) continue;
      seenReasons.add(key);
      rows.push(
        `- **${r.description}**${r.concept ? ` _(concept: ${r.concept})_` : ""}${
          r.reason ? ` — "${r.reason}"` : ""
        }`,
      );
    }
  } else {
    for (const a of rejectedFromStatus) {
      if (seenReasons.has(a.title)) continue;
      seenReasons.add(a.title);
      rows.push(`- **${a.title}**`);
    }
  }
  if (rows.length > 0) {
    sections.push("## Approaches you won't re-propose");
    sections.push("");
    rows.forEach((r) => sections.push(r));
    sections.push("");
  }

  if (conceptCounts.size === 0 && decisionsWithPredictions.length === 0 && rows.length === 0) {
    sections.push("_Nothing crystallized yet. Keep pairing — the agent's `log_reasoning.concept` field and your rejection reasons become the material here._");
    sections.push("");
  }

  sections.push(`*Generated from session ${state.sessionId} — [deepPairing](https://github.com/deeppairing).*`);
  return sections.join("\n");
}

function findRetrospective(state: SessionState, decisionId: string):
  | { verdict: "right" | "wrong" | "mixed"; note?: string }
  | undefined {
  const retros = (state as any).retrospectives as
    | Array<{ decisionId: string; verdict: "right" | "wrong" | "mixed"; note?: string }>
    | undefined;
  return retros?.find((r) => r.decisionId === decisionId);
}
