import { useState } from "react";

/**
 * Renders an agent-authored HTML/CSS/JS prototype in a hardened sandbox.
 *
 * Threat model: the `html` is generated by the agent, so it's untrusted code.
 * Two independent layers contain it:
 *
 *  1) `sandbox="allow-scripts"` WITHOUT `allow-same-origin` → the iframe runs at
 *     a unique OPAQUE origin. Scripts execute, but they cannot reach the parent
 *     DOM, read the daemon's cookies / localStorage, or make same-origin
 *     (credentialed) requests. This is the hard isolation.
 *  2) A locked-down CSP injected into the document: `default-src 'none'` with no
 *     `connect-src` blocks ALL network egress (fetch / XHR / WebSocket / beacon),
 *     so a prototype can't phone home or pull in third-party resources. Inline
 *     style/script are allowed so a self-contained prototype actually runs;
 *     `form-action 'none'` and `base-uri 'none'` close the obvious side doors.
 *
 * On top of that: a hard SIZE CAP, and CLICK-TO-RUN so agent code never executes
 * until the human opts in (and sees the "sandboxed · no network" banner first).
 */
const MAX_HTML_BYTES = 512 * 1024;

const CSP = [
  "default-src 'none'",
  "img-src data: blob:",
  "style-src 'unsafe-inline'",
  "font-src data:",
  "script-src 'unsafe-inline'",
  "form-action 'none'",
  "base-uri 'none'",
].join("; ");

function wrapHtml(html: string): string {
  // Wrap the agent payload in a document we control so OUR CSP meta is first in
  // <head> and governs the whole document (it combines with anything the agent
  // included — most restrictive wins). The sandbox attribute is the primary
  // defense regardless; this is defense-in-depth against network egress.
  return (
    `<!doctype html><html><head><meta charset="utf-8">` +
    `<meta http-equiv="Content-Security-Policy" content="${CSP}">` +
    `<style>html,body{margin:0;padding:10px;font-family:system-ui,-apple-system,sans-serif;color:#111;background:#fff}</style>` +
    `</head><body>${html}</body></html>`
  );
}

export function PrototypeFrame({ html }: { html: string }) {
  const [running, setRunning] = useState(false);
  const [showSource, setShowSource] = useState(false);

  const tooBig = new Blob([html]).size > MAX_HTML_BYTES;

  if (!html.trim()) {
    return <div className="text-2xs text-text-muted">No prototype HTML provided.</div>;
  }

  return (
    <div className="space-y-1.5">
      <div className="flex items-center gap-2 text-[10px] text-text-muted">
        <span className="px-1.5 py-0.5 rounded bg-surface-elevated">🔒 sandboxed · no network</span>
        <span>Agent-generated — runs in an isolated frame.</span>
      </div>

      {tooBig ? (
        <div className="text-2xs text-accent-amber rounded border border-dashed border-border-default p-3 text-center">
          Prototype is too large to render safely ({Math.round(new Blob([html]).size / 1024)} KB &gt; 512 KB cap).
        </div>
      ) : running ? (
        <iframe
          // No `allow-same-origin` — opaque origin, no parent/cookie/storage access.
          sandbox="allow-scripts"
          srcDoc={wrapHtml(html)}
          title="Sandboxed prototype"
          className="w-full h-[420px] rounded border border-border-default bg-white"
        />
      ) : (
        <button
          onClick={() => setRunning(true)}
          className="w-full rounded border border-dashed border-accent-violet/40 bg-accent-violet-dim/15 p-4 text-center
                     text-xs text-accent-violet hover:bg-accent-violet-dim/25 transition-colors"
        >
          ▶ Run prototype (sandboxed)
        </button>
      )}

      <button
        onClick={() => setShowSource((s) => !s)}
        className="text-[10px] text-text-muted hover:text-text-secondary"
      >
        {showSource ? "Hide source" : "View source"}
      </button>
      {showSource && (
        <pre className="text-2xs font-mono bg-surface-code rounded p-2 overflow-x-auto whitespace-pre-wrap text-text-secondary max-h-48 overflow-y-auto">
          {html}
        </pre>
      )}
    </div>
  );
}
